services:
  - type: web
    name: dofus-retro-optimizer-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
